version: '3.7'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dzc-capital-db
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      target: builder
    command: echo "Proceed as one-off"
    volumes:
      - "./:/app"
    environment:
      DATABASE_URL: mysql://root:root@db:3306/dzc-capital-db
