source "https://rubygems.org"
ruby "2.5.3"

gem "sinatra"
gem 'sinatra-contrib'
gem "puma"
gem "pg"
gem "rake"
gem "activerecord"

group :test, :development do
  gem "rspec"
  gem "capybara"
  gem "rerun"
  gem "selenium-webdriver"
end
