engines:
  duplication:
    enabled: false
    checks:
        Similar code:
          enabled: false
    config:
      languages:
        javascript:
          mass_threshold: 20
ratings:
  paths:
  - "server/**.js"
exclude_paths:
- "server/tests/"
- "node_modules/"
- "template/"
- "public/"
- "docs/"
- "dist/"
- "webpack/"