language : "node_js"
node_js :
  - "8"
cache:
 directories:
  - "node_modules"
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
  - sequelize db:migrate
env:
  global:
    - export NODE_ENV=test
script: 
  - npm test
after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < coverage/lcov.info
  - npm run coveralls